### PR TITLE
Add prefix commit button to SCM (Closes #1)

### LINKED ISSUE #1: Not working for workspaces with multiple repositories with different branches
Hi, I really like your extension and it can be really useful and save some time by writing commit messages. Unfortunately it's not working properly if multiple project folders are opened and if they have their own git repositories in branches that do not match the specified pattern. 

E.g. all repositories are on branch "master" and only one repository is on branch "feature/ABC-123". If I want to commit on the feature branch on this repository then I get lots of error messages for the other repositories which look like this:

Somehow it's annoying if you've e.g. 10 repositories opened and the pattern only matches for one, then you'll get 9 error messages that you've to click away.

### PR DESCRIPTION
**Pull request by PKief**
Hey @srmeyers, I solved the problem described in #1 by adding a button to the SCM view that calls the command "gitPrefix.setMessage" only for the repository of the current SCM window.

See demo below:

demo

What do you think about this?

### CODE REVIEW

**Comment by srmeyers** [comment]
Thanks @PKief. This looks great!!

**Review by srmeyers — APPROVED** [review]

**Comment by PKief** [comment]
@srmeyers When do you've planned to push the updated extension on the VS Code marketplace?

**Comment by srmeyers** [comment]
@PKief I published it tonight.  I included your nice video in the README. What tool did you use to create create the gif video?

**Comment by PKief** [comment]
@srmeyers Thank you, it looks great! I recorded it with [ScreenToGif](https://www.screentogif.com/).

**Pull request merged**
